### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by Marcusz97** [karlp/ch341-linux#1]
Hi when I'm compiling your driver I have this error on different lines
error: 'struct usb_Serial_port' has no member named 'number'

I also try to compile the driver give me in the CD with the USB and it give me the  error:

fatal error: usb-serial.h: no such file or directory

Can you please help me?

Thanks a lot,
Marco

**Comment by karlp** [comment]
No.  This is a linux repo, that is now more than 12 versions out of date, and was only for development of a mainline driver.  Using some driver on a CD has nothing to do with this (obsolete) repo, and never will.
